name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            dependencies: ''
          - os: 'macos-latest'
            dependencies: ''
          - os: 'macos-latest'
            dependencies: 'nlesc/nlesc/trilinos'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get install ${{ matrix.dependencies }}
      if: ${{ matrix.os != 'macos-latest' && matrix.dependencies != '' }}
    
    - name: Install macOS dependencies
      run: |
        brew tap nlesc/nlesc
        brew install ${{ matrix.dependencies }}
      if: ${{ matrix.os == 'macos-latest' && matrix.dependencies != '' }}

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=E226,E261,E302,E731,C901
    
    - name: Test with pytest
      run: |
        pytest
